from cryptography.fernet import Fernet

# Generate an encryption key.
def generate_key():
    return Fernet.generate_key()

# Saving the key to a file.
def save_key(key, key_file):
    with open(key_file, "wb") as file:
        file.write(key)

#Load the enc key from a file.
def load_key(key_file):
    with open(key_file, "rb") as file:
        return file.read()
    
# File encryption.
def encrypt_file(input_file, output_file, key):
    with open(input_file, "rb") as file:
        data = file.read()

    fernet = Fernet(key)
    encrypted_data = fernet.encrypt(data)

    with open(output_file, "wb") as file:
        file.write(encrypted_data)

# Decrypt the file.
def decrypt_file(input_file, output_file, key):
    with open(input_file, "rb") as file:
        encrypted_data = file.read()

    fernet = Fernet(key)
    decrypted_data = fernet.decrypt(encrypted_data)

    with open(output_file, "wb") as file:
        file.write(decrypted_data)

# Run the code

if __name__ == "__main__":
    key = generate_key()
    key_file = "encryption_key.key"
    save_key(key, key_file)


    # Name of the file to be encrypted. In this case plaintext.txt
    input_file = "plaintext.txt" 

    # these two will be generated by the code
    encrypted_file = "encrypted_file.txt"
    decrypted_file = "decrypted_file.txt"

    encrypt_file(input_file, encrypted_file, key)
    print(f"The input file '{input_file}' has been encrypted to '{encrypted_file}' ")

    decrypt_file(encrypted_file, decrypted_file, key)
    print(f"The input file '{encrypted_file}' has been  decrypted to '{decrypted_file}'")
